Backend/Models/TournamentView.cs
using Domain;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web;

namespace Backend.Models
{
    [NotMapped]
    public class TournamentView : Tournament
    {
        [Display(Name = "Logo")]
        public HttpPostedFileBase LogoFile { get; set; }
    }
}

Backend/Controllers/GenericController.cs
using Backend.Models;
using System.Linq;
using System.Web.Mvc;

namespace Backend.Controllers
{
    public class GenericController : Controller
    {
       
        private DataContextLocal db = new DataContextLocal();
        public JsonResult GetTeams(int leagueId)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var teams = db.Teams.Where(t => t.LeagueId == leagueId);
            return Json(teams);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }

    }
}

Backend/Controllers/TournamentsController.cs
using Backend.Helpers;
using Backend.Models;
using Domain;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System;
using System.Web.UI;

namespace Backend.Controllers
{
    [Authorize]

    public class TournamentsController : Controller
    {
        private DataContextLocal db;
        FilesHelper fileshelper = new FilesHelper();

        public TournamentsController()
        {
            db = new DataContextLocal();
        }


        public async Task<ActionResult> DeleteMatch(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var match = await db.Matches.FindAsync(id);

                if (match == null)
                {
                    return HttpNotFound();
                }

                db.Matches.Remove(match);
                await db.SaveChangesAsync();
                return RedirectToAction(string.Format("DetailsDate/{0}", match.DateId));
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return RedirectToAction(string.Format("DetailsDate/{0}", 1));
            }
        }

        public async Task<ActionResult> EditMatch(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Match match = await db.Matches.FindAsync(id);
            if (match == null)
            {
                return HttpNotFound();
            }
            ViewBag.DateId = new SelectList(db.Dates, "DateId", "Name", match.DateId);
            ViewBag.LocalId = new SelectList(db.Teams, "TeamId", "Name", match.LocalId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", match.StatusId);
            ViewBag.TournamentGroupId = new SelectList(db.TournamentGroups, "TournamentGroupId", "Name", match.TournamentGroupId);
            ViewBag.VisitorId = new SelectList(db.Teams, "TeamId", "Name", match.VisitorId);
            return View(match);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditMatch(Match match)
        {
            if (ModelState.IsValid)
            {
                db.Entry(match).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction(string.Format("DetailsDate/{0}", match.DateId));
            }

            ViewBag.DateId = new SelectList(db.Dates, "DateId", "Name", match.DateId);
            ViewBag.LocalId = new SelectList(db.Teams, "TeamId", "Name", match.LocalId);
            ViewBag.StatusId = new SelectList(db.Status, "StatusId", "Name", match.StatusId);
            ViewBag.TournamentGroupId = new SelectList(db.TournamentGroups, "TournamentGroupId", "Name", match.TournamentGroupId);
            ViewBag.VisitorId = new SelectList(db.Teams, "TeamId", "Name", match.VisitorId);
            return View(match);
        }

        public async Task<ActionResult> CreateMatch(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var dates = await db.Dates.FindAsync(id);
                if (dates == null)
                {
                    return HttpNotFound();
                }

                ViewBag.LocalLeagueId = new SelectList(db.Leagues.OrderBy(t => t.Name), "LeagueId", "Name");
                ViewBag.LocalId = new SelectList(db.Teams.Where(y => y.LeagueId == db.Leagues.FirstOrDefault().LeagueId).OrderBy(t => t.Name), "TeamId", "Name");
                ViewBag.VisitorLeagueId = new SelectList(db.Leagues.OrderBy(t => t.Name), "LeagueId", "Name");
                ViewBag.VisitorId = new SelectList(db.Teams.Where(y => y.LeagueId == db.Leagues.FirstOrDefault().LeagueId).OrderBy(t => t.Name), "TeamId", "Name");
                ViewBag.TournamentGroupId = new SelectList(db.TournamentGroups.Where(tg => tg.TournamentId == dates.TournamentId).OrderBy(n => n.Name), "TournamentGroupId", "Name");
                var view = new MatchView { DateId = dates.DateId };
                return View(view);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateMatch(MatchView view)
        {
            try
            {
                if (view.DateString == null)
                {
                    ShowMessage();
                    return RedirectToAction(string.Format("DetailsDate/{0}", view.DateId));
                }
                if (ModelState.IsValid)
                {
                    view.StatusId = 1;
                    view.DateTime = Convert.ToDateTime(string.Format("{0} {1}", view.DateString, view.TimeString));
                    var match = ToMatch(view);
                    db.Matches.Add(match);
                    await db.SaveChangesAsync();
                    return RedirectToAction(string.Format("DetailsDate/{0}", match.DateId));
                }

                ViewBag.LocalLeagueId = new SelectList(db.Leagues.OrderBy(t => t.Name), "LeagueId", "Name", view.LocalLeagueId);
                ViewBag.LocalId = new SelectList(db.Teams.Where(y => y.LeagueId == view.LocalLeagueId).OrderBy(t => t.Name), "TeamId", "Name", view.LocalId);
                ViewBag.VisitorLeagueId = new SelectList(db.Leagues.OrderBy(t => t.Name), "LeagueId", "Name", view.VisitorLeagueId);
                ViewBag.VisitorId = new SelectList(db.Teams.Where(y => y.LeagueId == view.VisitorLeagueId).OrderBy(t => t.Name), "TeamId", "Name", view.VisitorId);
                ViewBag.TournamentGroupId = new SelectList(db.TournamentGroups.Where(tg => tg.TournamentGroupId == view.TournamentGroupId).OrderBy(n => n.Name), "TournamentGroupId", "Name");

                return View(view);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return RedirectToAction(string.Format("DetailsDate/{0}", view.DateId));
                throw;
            }
        }

        private void ShowMessage()
        {
        }

        private Match ToMatch(MatchView view)
        {
            return new Match
            {
                Date = view.Date,
                DateId = view.DateId,
                DateTime = view.DateTime,
                LocalId = view.LocalId,
                Predictions = view.Predictions,
                StatusId = view.StatusId,
                TournamentGroupId = view.TournamentGroupId,
                VisitorId = view.VisitorId,
            };
        }


        public async Task<ActionResult> DeleteDate(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var date = await db.Dates.FindAsync(id);

                if (date == null)
                {
                    return HttpNotFound();
                }

                db.Dates.Remove(date);
                await db.SaveChangesAsync();
                return RedirectToAction(string.Format("Details/{0}", date.TournamentId));
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);
                return View();
            }
        }
        public async Task<ActionResult> EditDate(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var date = await db.Dates.FindAsync(id);

                if (date == null)
                {
                    return HttpNotFound();
                }

                return View(date);
            }
            catch (Exception ex)
            {

                fileshelper.ErrorLogging(ex);
                return View();

            }
        }

        public async Task<ActionResult> DetailsGroup(int? id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var tournamentGroup = await db.TournamentGroups.FindAsync(id);
                if (tournamentGroup == null)
                {
                    return HttpNotFound();
                }
                return View(tournamentGroup);
            }
            catch (Exception ex)
            {

                fileshelper.ErrorLogging(ex);
                return View();

            }
        }



        public async Task<ActionResult> DetailsDate(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var dates = await db.Dates.FindAsync(id);
            if (dates == null)
            {
                return HttpNotFound();
            }
            return View(dates);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditDate(Date date)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(date).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction(string.Format("Details/{0}", date.TournamentId));
                }

                return View(date);
            }
            catch (Exception ex)
            {
                fileshelper.ErrorLogging(ex);

Backend/Views/Tournaments/Create.cshtml
﻿@model Backend.Models.TournamentView
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm("Create", "Tournaments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tournament</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LogoFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="file-input-new">
                    <div class="input-group" style="width:280px">
                        <div tabindex="500" class="form-control file-caption">
                            <div class="file-caption-name" id="NombreArchivo">
                            </div>
                        </div>
                        <div class="input-group-btn" style="height:auto">
                            <div tabindex="500" class="btn btn-primary btn-file">
                                <i class="glyphicon glyphicon-folder-open"></i>
                                File Search...
                                @Html.TextBoxFor(modelo => modelo.LogoFile, new { type = "file", id = "files" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Tournaments/CreateDate.cshtml
﻿@model Domain.Date
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Date</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TournamentId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to Tournament", "Details", new { id = Model.TournamentId }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Tournaments/CreateGroup.cshtml
﻿@model Domain.TournamentGroup
@{
    ViewBag.Title = "Create";
}
<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>TournamentGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TournamentId)
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to Tournament", "Details", new { id = Model.TournamentId }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

Backend/Views/Tournaments/CreateMatch.cshtml
﻿@model Backend.Models.MatchView
@{
    ViewBag.Title = "Create";

}
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Match</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DateId)

        <div class="form-group">
            @Html.LabelFor(model => model.DateString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class='input-group date' id='datepicker' style="width:280px">
                    @Html.EditorFor(model => model.DateString, new { htmlAttributes = new { @class = "form-control" } })
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                @Html.ValidationMessageFor(model => model.DateString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalLeagueId, "Local League", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocalLeagueId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocalLeagueId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.LocalId, "Local", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocalId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocalId, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.VisitorLeagueId, "Visitor League", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VisitorLeagueId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VisitorLeagueId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VisitorId, "Visitor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("VisitorId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VisitorId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TournamentGroupId, "Tournament Group", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TournamentGroupId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TournamentGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
                @Html.ActionLink("Back to Date", "DetailsDate", new { id = Model.DateId }, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $(function () {
            $('#datepicker').datetimepicker({ format: 'YYYY/MM/DD' });
        });
    </script>
}

Backend/Views/Tournaments/Delete.cshtml
@model Domain.Tournament

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>

        <dd>
            @if (!string.IsNullOrEmpty(Model.Logo))
            {
                <img src="@Url.Content(Model.Logo)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
        </div>
    }
</div>

Backend/Views/Tournaments/Details.cshtml
﻿@model Domain.Tournament
@{
    ViewBag.Title = "Details";
}
<h2>Details</h2>
<div>
    <h4>Tournament</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Logo)
        </dt>
        <dd>
            @if (!string.IsNullOrEmpty(Model.Logo))
            {
                <img src="@Url.Content(Model.Logo)" alt="Image" style="width:100px;height:100px;max-width: 100%; height: auto;" />
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit Tournament", "Edit", new { id = Model.TournamentId }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Create Group", "CreateGroup", new { id = Model.TournamentId }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Create Date", "CreateDate", new { id = Model.TournamentId }, new { @class = "btn btn-default" })
    @Html.ActionLink("Back to List", "Index", new { }, new { @class = "btn btn-success" })
</p>

<div class="row">
    <div class="col-md-6">
        <h4>Groups</h4>
        @if (Model.Groups.Count == 0)
        {
            <h5>No groups registered yet</h5>
        }
        else
        {
            <table class="table table-hover">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Groups.FirstOrDefault().Name)
                    </th>
                    <th>
                        #Teams
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model.Groups.OrderBy(g => g.Name))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TournamentTeams.Count)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "EditGroup", new { id = item.TournamentGroupId }, new { @class = "btn btn-warning" })
                            @Html.ActionLink("Details", "DetailsGroup", new { id = item.TournamentGroupId }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Delete", "DeleteGroup", new { id = item.TournamentGroupId }, new { @class = "btn btn-danger", onclick = "return confirm('Are you sure to delete this record');" })
                        </td>
                    </tr>
                }
            </table>

        }
    </div>
    <div class="col-md-6">
        <h4>Dates</h4>
        @if (Model.Dates.Count == 0)
        {
            <h5>No dates registered yet</h5>
        }
        else
        {
            <table class="table table-bordered table table-hover">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Dates.FirstOrDefault().Name)
                    </th>
                    <th>
                        # Matches
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model.Dates.OrderBy(g => g.Name))
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Matches.Count)
                        </td>
                        <td>
                            @Html.ActionLink("Edit", "EditDate", new { id = item.DateId }, new { @class = "btn btn-warning" })
                            @Html.ActionLink("Details", "DetailsDate", new { id = item.DateId }, new { @class = "btn btn-info" })
                            @Html.ActionLink("Delete", "DeleteDate", new { id = item.DateId }, new { @class = "btn btn-danger", onclick = "return confirm('Are you sure to delete this record');" })
                        </td>
                    </tr>
                }
            </table>

        }

    </div>
</div>

Backend/Views/Tournaments/EditDate.cshtml
@model Domain.Date

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Date</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DateId)
        @Html.HiddenFor(model => model.TournamentId)


        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-info" />
                @Html.ActionLink("Back to Tournament", "Details", new { id = Model.TournamentId }, new { @class = "btn btn success" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Backend/Views/Tournaments/EditTeam.cshtml
@model Backend.Models.TournamentTeamView

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Tournament Team</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TournamentTeamId)
        @Html.HiddenFor(model => model.TournamentGroupId)

        <div class="form-group">
            @Html.LabelFor(model => model.LeagueId, "League", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LeagueId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LeagueId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamId, "Team", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeamId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatchesPlayed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatchesPlayed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatchesPlayed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatchesWon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatchesWon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatchesWon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatchesLost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatchesLost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatchesLost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MatchesTied, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MatchesTied, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MatchesTied, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FavorGoals, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FavorGoals, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FavorGoals, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AgainstGoals, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AgainstGoals, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AgainstGoals, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Points, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Points, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Points, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Position, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Position, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Position, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-warning" />
                @Html.ActionLink("Back to Group", "DetailsGroup", new { id = Model.TournamentGroupId }, new { @class = "btn btn success" })
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        var Url = '@Url.Action("GetTeams", "Generic")';
    </script>
}